import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local"

const outfitFont = localFont({
  src: '../assets/fonts/Outfit-VariableFont_wght.ttf',
  variable: '--font-outfit',
});

export const metadata: Metadata = {
  title: "Grascope Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={outfitFont.variable}>
      <body
        className=''
      >
        {children}
      </body>
    </html>
  );
}
